{% set name = "minio" %}
{% set version = "7.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/minio-{{ version }}.tar.gz
  sha256: a83c2fcd981944602a8dc11e8e07543ed9cda0a9462264e3f46a13171c56bccb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - certifi
    - urllib3
    - argon2-cffi
    - pycryptodome

test:
  imports:
    - minio
    - minio.api
    - minio.helpers
    - minio.error
    - minio.sse
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/minio/minio-py
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: MinIO Python Library for Amazon S3 Compatible Cloud Storage for Python

  description: |
    The MinIO Python Client SDK provides simple APIs to access any Amazon S3
    compatible object storage server.
  doc_url: https://docs.min.io/docs/python-client-api-reference
  dev_url: https://github.com/minio/minio-py

extra:
  recipe-maintainers:
    - guzman-raphael
    - rxm7706
