{% set name = "minio" %}
{% set version = "7.2.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/minio-{{ version }}.tar.gz
  sha256: 756f97fb3d19d198facd1b6ff44006a58934a5b09d512e343227cdaf92f3da13

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - typing_extensions
    - python >={{ python_min }}
    - certifi
    - urllib3
    - argon2-cffi
    - pycryptodome

test:
  imports:
    - minio
    - minio.api
    - minio.helpers
    - minio.error
    - minio.sse
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/minio/minio-py
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: MinIO Python Library for Amazon S3 Compatible Cloud Storage for Python

  description: |
    The MinIO Python Client SDK provides simple APIs to access any Amazon S3
    compatible object storage server.
  doc_url: https://docs.min.io/docs/python-client-api-reference
  dev_url: https://github.com/minio/minio-py

extra:
  recipe-maintainers:
    - guzman-raphael
    - rxm7706
